# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: superdurszlak - Distributed Systems by Szymon Durak
short_title: superdurszlak.dev
email: szymon@superdurszlak.dev
tagline: Szymon Durak - a Software Engineer for distributed systems.
description: >- # this means to ignore newlines until "baseurl:"
  I am a Software Engineer operating in Kraków, Poland. My preferred areas of expertise include 
  designing, implementing and deploying distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.superdurszlak.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username: superdurszlak
linkedin_username: szymon-durak

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-toc
  - jemoji
timezone: Europe/Warsaw
lsi: false
safe: false
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:slug/
      toc: true
      seo:
        type: BlogPosting
  - scope:
      path: ""
      type: "pages" 
    values:
      show_in_nav: true
  - scope:
      path: ""
    values:
      case_study: false
      jargon_heavy: false
      highly_subjective: false
      stock: ""
      image: 
        path: /assets/images/logo.svg
        alt: >
          Website logo, in the form of a dark teal colander with light gray inside. 
          Within the colander, dark teal 'SD' initials are visible, referring to both 
          'superdurszlak' nickname and 'Szymon Durak' full name, stylized after a diagram 
          in reference to distributed systems and system design.
      seo:
        type: WebSite
      seo_description_max_words: 150

# Giscus properties
giscus:
  enabled: true
  data_repo: "superdurszlak/superdurszlak.github.io"
  data_repo_id: "R_kgDOMq4ilg"
  data_category: "Announcements"
  data_category_id: "DIC_kwDOMq4ils4CiJ6m"
  data_mapping: "url"
  data_strict: "1"
  data_reactions_enabled: "1"
  data_emit_metadata: "0"
  data_input_position: "top"
  data_theme: "light"
  data_lang: "en"
  data_loading: "lazy"
  cross_origin: "anonymous"

# SEO
logo: /assets/images/logo.svg
social:
  name: Szymon Durak
  links:
   - https://github.com/superdurszlak
   - https://www.linkedin.com/in/szymon-durak/

# jekyll-spaceship
jekyll-spaceship:
  plantuml-processor:
    mode: pre-fetch
    src: http://www.plantuml.com/plantuml/svg/
    output_dir: "assets/plantuml"

# Redirects
redirect_from:
  json: false

# Stock photos
stocks_dir: /assets/stock/
stocks:
  - name: autism-letters
    alt: Photo of colorful letters lined up to form 'Autism' word, surrounded by scattered letters
    credit: >
      Photo by 
      <a href="https://unsplash.com/@anniespratt?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Annie Spratt</a> 
      on 
      <a href="https://unsplash.com/photos/text-nP9J7O90HfY?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  - name: cloud-thunderstorm
    alt: Photo of a night sky lit up by lightning, giving it a deep violet hue
    credit: >
      Photo by 
      <a href="https://unsplash.com/@noaa?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">NOAA</a> 
      on 
      <a href="https://unsplash.com/photos/lightning-at-night-p9BRX1mBfe4?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  - name: java-code-screen
    alt: Photo of a computer screen, showing mostly blurred out Java code in an IDE window
    credit: >
      Photo by 
      <a href="https://unsplash.com/@orbtalmedia?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">orbtal media</a>
      on 
      <a href="https://unsplash.com/photos/monitor-showing-computer-application-1td5Iq5IvNc?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  - name: jenga
    alt: Photo of a toppled over Jenga tower
    credit: >
      Photo by 
      <a href="https://unsplash.com/@naveenkumar?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Naveen Kumar</a> 
      on 
      <a href="https://unsplash.com/photos/brown-wooden-blocks-on-table-zo1jo5dWwwE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  - name: metrics-screen
    alt: Photo of a dashboard on a computer screen
    credit: >
      Photo by 
      <a href="https://unsplash.com/@dawson2406?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Stephen Dawson</a> 
      on 
      <a href="https://unsplash.com/photos/turned-on-monitoring-screen-qwtCeJ5cLYs?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  - name: server-rack
    alt: Photo of server racks full of colorful Ethernet wires and green diodes
    credit: >
      Photo by 
      <a href="https://unsplash.com/@tvick?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Taylor Vick</a> 
      on 
      <a href="https://unsplash.com/photos/cable-network-M5tzZtFCOfs?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>

share:
  - text: Share on LinkedIn
    type: linkedin
  - text: Share on Twitter/X
    type: x
  - text: Share on Facebook
    type: facebook
  - text: Share on Reddit
    type: reddit
  - text: Share on HackerNews
    type: hackernews

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
